{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "name": "opentis"
    },
    "spec": {
        "selector": {
            "app": "opentis"
        },
        "ports": [
            {
                "protocol": "TCP",
                "port": 3000,
                "targetPort": 3000
            }
        ]
    }
}